pipeline {
    agent any
    tools {
        nodejs "node" // "tools" should be used instead of "tool"
    }
    stages {
        stage("Install dependency") {
            steps {
                sh "npm install"
            }
        }
        stage("Running tests") {
            steps {
                sh 'npm run test'
            }
        }
                stage("Running tests") {
            steps {
                sh 'npm build'
            }
        }
    }
}
