name: Auto-Merge Dev to Testing

on:
  push:
    branches:
      - dev

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge code to main branch
        run: |
          git checkout main
          git merge dev 
          git push origin main
